### ISSUE TITLE
No Run

### ISSUE THREAD

**Issue by KayNguyen97** [ymmmmmmmm/BeraChainTools#18]
Hi bro, i can't run program 
pls help me
show error :
Traceback (most recent call last):
  File "D:\Data Engineer\BT_Python\Tools\BeraChainTools-main\bera_tools.py", line 11, in <module>
    from eth_account import Account
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_account\__init__.py", line 5, in <module>
    from eth_account.account import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_account\account.py", line 20, in <module>
    from eth_keyfile import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_keyfile\__init__.py", line 5, in <module>
    from eth_keyfile.keyfile import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_keyfile\keyfile.py", line 21, in <module>
    from Crypto import (
ModuleNotFoundError: No module named 'Crypto'
PS D:\Data Engineer\BT_Python\Tools\BeraChainTools-main> pip install pycryptodome
Requirement already satisfied: pycryptodome in d:\data engineer\ai\anaconda\lib\site-packages (3.17)
PS D:\Data Engineer\BT_Python\Tools\BeraChainTools-main> python bera_tools.py     
Traceback (most recent call last):
  File "D:\Data Engineer\BT_Python\Tools\BeraChainTools-main\bera_tools.py", line 11, in <module>
    from eth_account import Account
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_account\__init__.py", line 5, in <module>
    from eth_account.account import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_account\account.py", line 20, in <module>
    from eth_keyfile import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_keyfile\__init__.py", line 5, in <module>
    from eth_keyfile.keyfile import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_keyfile\keyfile.py", line 21, in <module>
    from Crypto import (
ModuleNotFoundError: No module named 'Crypto'
PS D:\Data Engineer\BT_Python\Tools\BeraChainTools-main> python bera_tools.py
Traceback (most recent call last):
  File "D:\Data Engineer\BT_Python\Tools\BeraChainTools-main\bera_tools.py", line 11, in <module>
    from eth_account import Account
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_account\__init__.py", line 5, in <module>
    from eth_account.account import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_account\account.py", line 20, in <module>
    from eth_keyfile import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_keyfile\__init__.py", line 5, in <module>
    from eth_keyfile.keyfile import (
  File "D:\Data Engineer\AI\Anaconda\lib\site-packages\eth_keyfile\keyfile.py", line 21, in <module>
    from Crypto import (
ModuleNotFoundError: No module named 'Crypto'

**Comment by ymmmmmmmm** [comment]
Use python3.8+ and pip install -r requirements.txt
